distributed:
  num_agents: 3
  sync_interval: 100
  max_concurrent_actions: 5

real_time:
  max_inference_latency_ms: 100.0
  max_memory_usage_mb: 2048.0
  max_cpu_usage_percent: 50.0

retraining:
  performance_threshold: 0.8
  min_samples_before_retrain: 10000
  max_retrain_frequency_hours: 24

scaling:
  auto_scaling: true
  min_agents: 2
  max_agents: 10
  scale_thresholds:
    up: 0.8
    down: 0.3

monitoring:
  metrics_interval: 60
  log_level: "INFO"
  performance_logging: true
  action_logging: true

multi_tenant:
  max_tenants_per_agent: 5
  isolation_level: "strict"

safety:
  enable_fallback: true
  fallback_timeout_ms: 50.0
  max_consecutive_timeouts: 3 